os: osx
osx_image: xcode8
language: node_js
node_js:
- node
before_script:
- npm install -g grunt-cli npm
- export CSC_IDENTITY_AUTO_DISCOVERY=false
- npm run publish-osx
env:
  global:
    secure: J79NeoXU/k9mr48U7ZG2JpivEZiZEc2ipdz8Am+g8wlKnBzoE6jj2Al7eysKwTLr+zizmo+xYRMKJMYd6F9wQ57WzHo4T1Xw7b+nPnRVxlzS/sm6NlbZ3GNRLQ9QivVpQicu/IRBB5eN+FEJ9G5Evr2lz2Ze2An3f7TYYpK4MitsTMl8eElj24CKryqp+n/MDQ0IoH5Pce/HuVgL+v7N6XmLPiuOJQbbHPUaktzo5gU+LPkQim5BdTcM3VRzLw/m2TYNuuRNUzgMcRw0pEZcqoZ/FtUtBUES7tDEpwUMsrQ/YfzvmmPVNE82Dc+iaYID93hS+GG6+Y4SZikXdBjMubAbfAC8obqVUgbIR0p1FlaNj4yZfs44Lr69S0r85zvOlzvS6hvbKz+pLsbPanduOx6vtK2cCEJfeJG4iXKRhUYdKiPJkRE61S+7uRHV8ysBDZszQlU/c/HzmH27CykrhJEOcqRHCkfMCbF1T+OiHnDK1X0iqzo3urTIWjzgNIexWETQs9ls68D9HaSz2biG0qYStR0q1qA0lZSvq6fWHc1YTm8kg6Q98/TjXYChsDUT/xLe/31hSO8AmjwQ8ESsfvot6yl5w+qgM8tFeAGA1faWHOCtLhbbIFVagXQ/3iuihjxHgy+ALvB9fysUpMRingzE3o3z84RxYJjP3fug0r0=
