apiVersion: v1
kind: ConfigMap
metadata:
  name: p3x-redis-ui-settings
  namespace: p3x-redis-ui
data:
  .p3xrs-conns.json: |
    {
      "list": [
        {
          "name": "cluster",
          "host": "YOUR_REDIS_HOST",
          "port": 6379,
          "password": "YOUR_REDIS_PASSWORD_OR_EMPTY"
        }
      ]
    }
